collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.07885305
color:
  saturation: 0.6200717
  brandStrength: 0
  lightness: 0.7168459
  brandColors:
    - '#D7E1EA'
    - '#18181D'
    - '#B3D043'
    - '#438954'
    - '#78879A'
  rhythmicContrast: 0.3189964
layout_spectrum: 0.311828
name: PhotoPractice
